# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('type', models.PositiveIntegerField(choices=[(1, 'Input'), (1, 'Output'), (3, 'Input/Output')])),
            ],
        ),
    ]
