# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='interactiondevice',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Input'), (2, 'Output'), (3, 'Input/Output')]),
        ),
        migrations.AddField(
            model_name='interactiondevice',
            name='device_technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction_devices.DeviceTechnology'),
        ),
    ]
