# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, upload_to=resources.models.get_resource_path),
        ),
    ]
