# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import rehab_exergames.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=rehab_exergames.models.get_image_path)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('type', models.PositiveIntegerField(choices=[(1, 'Input'), (2, 'Output'), (3, 'Input/Output')])),
            ],
        ),
        migrations.CreateModel(
            name='ThematicContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='interaction_devices',
            field=models.ManyToManyField(to='rehab_exergames.InteractionDevice'),
        ),
    ]
