# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathologies', '0001_initial'),
        ('rehab_exergames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabilitationExergame',
            fields=[
                ('exergame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rehab_exergames.Exergame')),
                ('rehabilitation_type', models.CharField(choices=[('wide_physical', 'Physical - Wide Focus'), ('tight_physical', 'Wide Focus - Tight Focus'), ('behavioral', 'Behavioral'), ('cognitive', 'Cognitive')], max_length=20)),
                ('autonomy_degree', models.CharField(choices=[('constant_supervision', '1. Only motivates, requires constant physiotherapist supervision'), ('adaptation', '2. Provides adaptation features or constraints motion, requires constant physiotherapist supervision'), ('async_supervision', '3. Requires asynchronous physiotherapist supervision remotely or along periodic meetings'), ('no_supervision', '4. Standalone, does not require physiotherapist supervision')], max_length=20)),
            ],
            bases=('rehab_exergames.exergame',),
        ),
        migrations.CreateModel(
            name='RehabilitationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='rehabilitationexergame',
            name='assisted_rehabilitation_tasks',
            field=models.ManyToManyField(to='rehab_exergames.RehabilitationTask'),
        ),
        migrations.AddField(
            model_name='rehabilitationexergame',
            name='associated_pathologies',
            field=models.ManyToManyField(to='pathologies.Pathology'),
        ),
    ]
