# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab_exergames', '0004_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitationexergame',
            name='rehabilitation_type',
            field=models.CharField(choices=[('wide_physical', 'Wide Focus'), ('tight_physical', 'Tight Focus')], max_length=20),
        ),
    ]
