# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0002_auto_20180506_1939'),
        ('px_evaluation', '0008_auto_20180529_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('resources', models.ManyToManyField(blank=True, to='resources.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('instrument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='px_evaluation.Instrument')),
                ('evaluation_objective', models.TextField()),
                ('target_respondents', models.TextField()),
                ('validity', models.CharField(max_length=140)),
                ('reliability', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[(('init',), 'Initiated'), (('in_design',), 'In Design'), (('in_pre_test',), 'In Pre-Testing'), (('finished',), 'Finished'), (('in_review',), 'In Review')], default=('init',), max_length=20)),
                ('additional_documents', models.ManyToManyField(related_name='questionnaire_additional_docs', to='resources.Resource')),
                ('pre_testing_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_pre_test_report', to='resources.Resource')),
                ('questionnaire_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_questionnaire_doc', to='resources.Resource')),
                ('reliability_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_reliability', to='questionnaires_standard.Measure')),
                ('validity_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_validity', to='questionnaires_standard.Measure')),
            ],
            bases=('px_evaluation.instrument',),
        ),
    ]
