# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires_standard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='type',
            field=models.CharField(choices=[(('validity',), 'validity'), (('reliability',), 'reliability')], default='validity', max_length=20),
            preserve_default=False,
        ),
    ]
