# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires_standard', '0004_auto_20180530_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='pre_testing_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_pre_test_report', to='resources.Resource'),
        ),
    ]
