# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires_standard', '0005_auto_20180530_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='additional_documents',
            field=models.ManyToManyField(null=True, related_name='questionnaire_additional_docs', to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='pre_testing_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_pre_test_report', to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_questionnaire_doc', to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='reliability_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_reliability', to='questionnaires_standard.Measure'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='validity_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_validity', to='questionnaires_standard.Measure'),
        ),
    ]
