# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import apps.rehab_exergames.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interaction_devices', '0001_initial'),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.rehab_exergames.models.get_image_path)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ThematicContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exergame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rehab_exergames.Game')),
                ('thematic_content', models.PositiveIntegerField(choices=[(1, 'Daily Life Activities'), (2, 'Realistic'), (3, 'Imaginary'), (4, 'Abstract')])),
                ('configurable', models.BooleanField()),
                ('provide_performance_assessment', models.BooleanField()),
                ('associated_movements', models.ManyToManyField(to='movements.Movement')),
            ],
            bases=('rehab_exergames.game',),
        ),
        migrations.AddField(
            model_name='game',
            name='input_interaction_devices',
            field=models.ManyToManyField(related_name='input_devices', to='interaction_devices.InteractionDevice'),
        ),
        migrations.AddField(
            model_name='game',
            name='output_interaction_devices',
            field=models.ManyToManyField(related_name='output_devices', to='interaction_devices.InteractionDevice'),
        ),
    ]
