# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab_exergames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiondevice',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Input'), (2, 'Output'), (3, 'Input/Output')]),
        ),
    ]
