# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab_exergames', '0003_auto_20180326_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('categories', models.ManyToManyField(to='rehab_exergames.ConstraintCategory')),
            ],
        ),
    ]
